POST https://localhost:5002/api/customers/ HTTP/1.1
Content-Type: application/json

{
  "customerID": "BRTDL",
  "companyName": "Bertal Development",
  "contactName": "West",
  "contactTitle": "Sir",
  "address": "Krasnokazarmennaya 14Ak6",
  "city": "Moscow",
  "region": "RU",
  "postalCode": "115100",
  "country": "Russia",
  "phone": "(926) 114-1571"
}