GET https://localhost:5001/api/customers HTTP/1.1
###
GET https://localhost:5001/api/customers/?country=France HTTP/1.1
###
GET https://localhost:5001/api/Customers/abcxy
Accept: application/xml
###
GET https://localhost:5001/api/Customers/minet
Accept: application/json // by default